Remove older CUDA GPU code, now that it's replaced by CuPY GPU code
spacetelescope/poppy pull request #556
Opened 2023-03-25 13:21 UTC by mperrin

- Remove the older/obsolete CUDA GPU code
- Add initial placeholder for GPU usage documentation

2023-03-27 15:48 UTC, mperrin commented
@kian1377 can you please see if you have a GitHub collaboration invite to this repo? I ought to be able to tag you as a reviewer for a PR after you accept that. 

This is a followup PR to merging your CuPY GPU PR. This one (a) removes the older CUDA code which is obsoleted by the new code. We had agreed to do that as a separate PR; this is that PR. And (b) I started some brief initial documentation for the CuPy code. We can leave this pretty basic & minimal for now, or choose to expand it. What do you think?  FYI, Marcio (@obi-wan76) would like to organize a release of poppy relatively soon, so my inclination is to leave the docs fairly basic for now. I assume that's all fine with you as well.

2023-03-27 17:10 UTC, kian1377 commented
I just accepted the invitation. I am completely fine with leaving the docs
more basic for now, but let me know if there is something I should
contribute to the docs. As far as removing the older GPU functionality, I
think it will only involve removing some code from accel_math and
__init__.py.

On Mon, Mar 27, 2023 at 8:48 AM Marshall Perrin ***@***.***>
wrote:

> *External Email*
>
> @kian1377 <https://github.com/kian1377> can you please see if you have a
> GitHub collaboration invite to this repo? I ought to be able to tag you as
> a reviewer for a PR after you accept that.
>
> This is a followup PR to merging your CuPY GPU PR. This one (a) removes
> the older CUDA code which is obsoleted by the new code. We had agreed to do
> that as a separate PR; this is that PR. And (b) I started some brief
> initial documentation for the CuPy code. We can leave this pretty basic &
> minimal for now, or choose to expand it. What do you think? FYI, Marcio (
> @obi-wan76 <https://github.com/obi-wan76>) would like to organize a
> release of poppy relatively soon, so my inclination is to leave the docs
> fairly basic for now. I assume that's all fine with you as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spacetelescope/poppy/pull/556#issuecomment-1485380750>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMCLT2UOJ5PJSSBEKDQT2OLW6GZF5ANCNFSM6AAAAAAWHRAXYM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-25 13:05 UTC, obi-wan76 requested changes
The __init__.py file has some CUDA code, 
```
use_cuda = _config.ConfigItem(True, 'Use cuda for FFTs on GPU (assuming it' +
            'is available)?')
```
The CuPy code is there so I don't know if this could  be a conflict. I don't think this is an issue but since we are removing all CUDA code maybe we should remove it from here as well. If not necessary, I'll approve the merge as I've review all the other CUDA removal in the code and the additional placeholder for the documentation.

2023-05-10 19:01 UTC, BradleySappington approved these changes

2023-05-10 19:15 UTC, obi-wan76 approved these changes

2023-05-10 19:16 UTC, merged